In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

# malumotlar toplamini uygunlashtirish va birlashtirish

In [3]:
df_movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/master/IMDb/IMDb_movies.csv")

/var/folders/5r/8qsc7qzj04g73js6m7szr_7h0000gn/T/ipykernel_87684/4155099594.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_movies = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/master/IMDb/IMDb_movies.csv")

In [5]:
df_movies.shape

(85855, 15)

In [6]:
df_movies.index

RangeIndex(start=0, stop=85855, step=1)

In [7]:
df_movies.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN

In [8]:
df_rating = pd.read_csv("https://raw.githubusercontent.com/MansurCompAI/Practicum_Datasets/master/IMDb/IMDb_ratings.csv")

In [9]:
df_rating.shape

(85855, 3)

# merge

# ish beruvchi menga kino nomi yili va ortacha qiymati kerak

In [10]:
bigdata = pd.merge(df_movies, df_rating)

In [11]:
bigdata.head()

,imdb_title_id,title,original_title,year,date_published,genre,duration,country,language,director,writer,production_company,actors,description,budget,weighted_average_vote,total_votes
0,tt0000009,Miss Jerry,Miss Jerry,1894,1894-10-09,Romance,45,USA,None,Alexander Black,Alexander Black,Alexander Black Photoplays,"Blanche Bayliss, William Courtenay, Chauncey D...",The adventures of a female reporter in the 1890s.,NaN,5.9,154
1,tt0000574,The Story of the Kelly Gang,The Story of the Kelly Gang,1906,1906-12-26,"Biography, Crime, Drama",70,Australia,None,Charles Tait,Charles Tait,J. and N. Tait,"Elizabeth Tait, John Tait, Norman Campbell, Be...",True story of notorious Australian outlaw Ned ...,$ 2250,6.1,589
2,tt0001892,Den sorte drøm,Den sorte drøm,1911,1911-08-19,Drama,53,"Germany, Denmark",NaN,Urban Gad,"Urban Gad, Gebhard Schätzler-Perasini",Fotorama,"Asta Nielsen, Valdemar Psilander, Gunnar Helse...",Two men of high rank are both wooing the beaut...,NaN,5.8,188
3,tt0002101,Cleopatra,Cleopatra,1912,1912-11-13,"Drama, History",100,USA,English,Charles L. Gaskill,Victorien Sardou,Helen Gardner Picture Players,"Helen Gardner, Pearl Sindelar, Miss Fielding, ...",The fabled queen of Egypt's affair with Roman ...,$ 45000,5.2,446
4,tt0002130,L'Inferno,L'Inferno,1911,1911-03-06,"Adventure, Drama, Fantasy",68,Italy,Italian,"Francesco Bertolini, Adolfo Padovan",Dante Alighieri,Milano Film,"Salvatore Papa, Arturo Pirovano, Giuseppe de L...",Loosely adapted from Dante's Divine Comedy and...,NaN,7.0,2237

In [12]:
bigdata.columns

Index(['imdb_title_id', 'title', 'original_title', 'year', 'date_published',
       'genre', 'duration', 'country', 'language', 'director', 'writer',
       'production_company', 'actors', 'description', 'budget',
       'weighted_average_vote', 'total_votes'],
      dtype='object')

# mana nomi yili va ortacha qiymati

In [13]:
newcolums = bigdata[['title', 'year', 'weighted_average_vote']]
newcolums

                                title  year  weighted_average_vote
0                          Miss Jerry  1894                    5.9
1         The Story of the Kelly Gang  1906                    6.1
2                      Den sorte drøm  1911                    5.8
3                           Cleopatra  1912                    5.2
4                           L'Inferno  1911                    7.0
...                               ...   ...                    ...
85850                         Le lion  2020                    5.3
85851  De Beentjes van Sint-Hildegard  2020                    7.7
85852       Padmavyuhathile Abhimanyu  2019                    7.9
85853               Sokagin Çocuklari  2019                    6.4
85854      La vida sense la Sara Amat  2019                    6.7

[85855 rows x 3 columns]

# sodda misollar

In [14]:
A = pd.DataFrame({"Transport": ['poyezd','avtomobil','kema'],
     "Tezligi": ['130','100','60']})

In [15]:
A

   Transport Tezligi
0     poyezd     130
1  avtomobil     100
2       kema      60

In [24]:
B = pd.DataFrame({"Transport": ['poyezd','avtomobil','tranvay'],
     "Narxi": ['13000','10000','6000']})

# data setlar sodda bulganligi uchun bu tasavvur qilishimiz uchun qulay buladi

# endi datalarni merge qilib kuramiz

In [25]:
merge_df = pd.merge(A, B)#inter join ichki qushilish

In [26]:
merge_df

   Transport Tezligi  Narxi
0     poyezd     130  13000
1  avtomobil     100  10000

In [27]:
merge_df = pd.merge(A, B, how='outer')# outer join tashqi qushilish

In [28]:
merge_df

   Transport Tezligi  Narxi
0     poyezd     130  13000
1  avtomobil     100  10000
2       kema      60    NaN
3    tranvay     NaN   6000

# left maqsadi chap data yani A da uxshash bulmagan datalar ham olinadi Bda esa faqat uxshashlar olinadi

In [29]:
merge_left = pd.merge(A, B, how='left')# left join chapga birlashish

In [30]:
merge_left

   Transport Tezligi  Narxi
0     poyezd     130  13000
1  avtomobil     100  10000
2       kema      60    NaN

In [31]:
merge_right = pd.merge(A, B, how='right')# right join ongdan birlashish

In [32]:
merge_right

   Transport Tezligi  Narxi
0     poyezd     130  13000
1  avtomobil     100  10000
2    tranvay     NaN   6000

In [33]:
A = pd.DataFrame({"Transport_turlari": ['poyezd','avtomobil','kema'],
     "Tezligi": ['130','100','60']})

In [34]:
B = pd.DataFrame({"Transport": ['poyezd','avtomobil','tranvay'],
     "Narxi": ['13000','10000','6000']})

# agar bizda ustun nomlari bir xil bulmasa hato hisoblaydi buni tugirlash uchun qaysi ustun bilan boglashni aytish kerak

In [36]:
meg = pd.merge(A,B, left_on="Transport_turlari", right_on='Transport')
meg

  Transport_turlari Tezligi  Transport  Narxi
0            poyezd     130     poyezd  13000
1         avtomobil     100  avtomobil  10000

# mana endi hatoni tugirladik

# endi indekslar ustida birlashtirish

In [37]:
A = A.set_index('Transport_turlari')
A

                  Tezligi
Transport_turlari
poyezd                130
avtomobil             100
kema                   60

In [38]:
B

   Transport  Narxi
0     poyezd  13000
1  avtomobil  10000
2    tranvay   6000

In [39]:
meg1 = pd.merge(A, B, left_index=True, right_on='Transport')
meg1

  Tezligi  Transport  Narxi
0     130     poyezd  13000
1     100  avtomobil  10000

In [40]:
B = B.set_index('Transport')
B

           Narxi
Transport
poyezd     13000
avtomobil  10000
tranvay     6000

In [41]:
meg2 = pd.merge(A, B, left_index=True, right_index=True)

In [42]:
meg2

          Tezligi  Narxi
poyezd        130  13000
avtomobil     100  10000

In [43]:
meg2 = pd.merge(A, B, left_index=True, right_index=True, how='outer')
meg2

          Tezligi  Narxi
avtomobil     100  10000
kema           60    NaN
poyezd        130  13000
tranvay       NaN   6000