In [1]:
import pandas as pd 
import numpy as np

# uzun datasetdan keng dataset olish
# pivot

In [3]:
df = pd.read_csv('data_pivot.csv')
df

                              date     item      value
0    1959-03-31 23:59:59.999999999  realgdp   2710.349
1    1959-03-31 23:59:59.999999999     infl      0.000
2    1959-03-31 23:59:59.999999999    unemp      5.800
3    1959-06-30 23:59:59.999999999  realgdp   2778.801
4    1959-06-30 23:59:59.999999999     infl      2.340
..                             ...      ...        ...
604  2009-06-30 23:59:59.999999999     infl      3.370
605  2009-06-30 23:59:59.999999999    unemp      9.200
606  2009-09-30 23:59:59.999999999  realgdp  12990.341
607  2009-09-30 23:59:59.999999999     infl      3.560
608  2009-09-30 23:59:59.999999999    unemp      9.600

[609 rows x 3 columns]

In [4]:
pivot_data = df.pivot('date', 'item', 'value')
pivot_data

/var/folders/5r/8qsc7qzj04g73js6m7szr_7h0000gn/T/ipykernel_95672/3748741655.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  pivot_data = df.pivot('date', 'item', 'value')

item                           infl    realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]

# ana endi data kamaydi lekin datamiz tasirchanligi usha-usha chunki 1 sanda bir vaqtda 
# infl realgdp unemp bulgandi faqat addelni uzun qilib yozilgandi endi uzun qimay har birini index kurinishida chozib berdi

* suniy data

In [7]:
df['value 2'] = np.random.rand(len(df))

In [8]:
df

                              date     item      value   value 2
0    1959-03-31 23:59:59.999999999  realgdp   2710.349  0.974179
1    1959-03-31 23:59:59.999999999     infl      0.000  0.708344
2    1959-03-31 23:59:59.999999999    unemp      5.800  0.476528
3    1959-06-30 23:59:59.999999999  realgdp   2778.801  0.709841
4    1959-06-30 23:59:59.999999999     infl      2.340  0.070595
..                             ...      ...        ...       ...
604  2009-06-30 23:59:59.999999999     infl      3.370  0.856389
605  2009-06-30 23:59:59.999999999    unemp      9.200  0.159309
606  2009-09-30 23:59:59.999999999  realgdp  12990.341  0.360143
607  2009-09-30 23:59:59.999999999     infl      3.560  0.081532
608  2009-09-30 23:59:59.999999999    unemp      9.600  0.068085

[609 rows x 4 columns]

In [9]:
pivoted_data = df.pivot('date','item')
pivoted_data

/var/folders/5r/8qsc7qzj04g73js6m7szr_7h0000gn/T/ipykernel_95672/2286267977.py:1: FutureWarning: In a future version of pandas all arguments of DataFrame.pivot will be keyword-only.
  pivoted_data = df.pivot('date','item')

                              value                    value 2            \
item                           infl    realgdp unemp      infl   realgdp
date
1959-03-31 23:59:59.999999999  0.00   2710.349   5.8  0.708344  0.974179
1959-06-30 23:59:59.999999999  2.34   2778.801   5.1  0.070595  0.709841
1959-09-30 23:59:59.999999999  2.74   2775.488   5.3  0.609204  0.680060
1959-12-31 23:59:59.999999999  0.27   2785.204   5.6  0.789754  0.727611
1960-03-31 23:59:59.999999999  2.31   2847.699   5.2  0.779589  0.612271
...                             ...        ...   ...       ...       ...
2008-09-30 23:59:59.999999999 -3.16  13324.600   6.0  0.129811  0.895903
2008-12-31 23:59:59.999999999 -8.79  13141.920   6.9  0.114336  0.154239
2009-03-31 23:59:59.999999999  0.94  12925.410   8.1  0.639440  0.744603
2009-06-30 23:59:59.999999999  3.37  12901.504   9.2  0.856389  0.432083
2009-09-30 23:59:59.999999999  3.56  12990.341   9.6  0.081532  0.360143


item                              unemp
date
1959-03-31 23:59:59.999999999  0.476528
1959-06-30 23:59:59.999999999  0.122885
1959-09-30 23:59:59.999999999  0.824005
1959-12-31 23:59:59.999999999  0.995837
1960-03-31 23:59:59.999999999  0.332867
...                                 ...
2008-09-30 23:59:59.999999999  0.071118
2008-12-31 23:59:59.999999999  0.525612
2009-03-31 23:59:59.999999999  0.087715
2009-06-30 23:59:59.999999999  0.159309
2009-09-30 23:59:59.999999999  0.068085

[203 rows x 6 columns]

# endi qiymat 2ta bolgani uchun har bir qiymat uchun aloxida chiqarib berdi

In [13]:
pivoted_data['value']

item                           infl    realgdp  unemp
date
1959-03-31 23:59:59.999999999  0.00   2710.349    5.8
1959-06-30 23:59:59.999999999  2.34   2778.801    5.1
1959-09-30 23:59:59.999999999  2.74   2775.488    5.3
1959-12-31 23:59:59.999999999  0.27   2785.204    5.6
1960-03-31 23:59:59.999999999  2.31   2847.699    5.2
...                             ...        ...    ...
2008-09-30 23:59:59.999999999 -3.16  13324.600    6.0
2008-12-31 23:59:59.999999999 -8.79  13141.920    6.9
2009-03-31 23:59:59.999999999  0.94  12925.410    8.1
2009-06-30 23:59:59.999999999  3.37  12901.504    9.2
2009-09-30 23:59:59.999999999  3.56  12990.341    9.6

[203 rows x 3 columns]